#!/usr/bin/env bash
set -euo pipefail

# Import a manually-downloaded GGUF from the shared model directory into Ollama.
# After ollama copies the file into its CAS, the duplicate is collapsed by
# replacing the CAS copy with a symlink back to the canonical file in the
# local GGUF model directory.
#
# Usage:
#   import-to-ollama.sh <gguf-name>             # uses gguf-name (no .gguf) as ollama tag
#   import-to-ollama.sh foo                     # → ollama tag: foo
#   import-to-ollama.sh foo my-tag              # → ollama tag: my-tag
#
# Modelfile is generated at $LOCAL_LLM_AGENT_ROOT/modelfiles/gguf/<tag>.modelfile.
# Existing modelfiles are not overwritten; edit and re-run if you want changes.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../common/env.sh
source "${SCRIPT_DIR}/../common/env.sh"

CAS="${OLLAMA_MODELS}/blobs"
MANIFESTS="${OLLAMA_MODELS}/manifests/registry.ollama.ai"
LLM_MODELS="$LLM_MODELS_DIR"
MODELFILES_DIR="${LOCAL_LLM_AGENT_ROOT}/modelfiles/gguf"

if [[ $# -lt 1 ]]; then
  echo "Usage: $0 <gguf-basename> [ollama-tag]" >&2
  exit 1
fi

base="${1%.gguf}"
tag="${2:-$base}"
gguf="${LLM_MODELS}/${base}.gguf"

if [[ ! -f "$gguf" ]]; then
  echo "GGUF not found: $gguf" >&2
  exit 1
fi
if [[ -L "$gguf" ]]; then
  echo "Refusing to import a symlink (this file is already shared with Ollama)" >&2
  exit 1
fi

mkdir -p "$MODELFILES_DIR"
modelfile="${MODELFILES_DIR}/${tag}.modelfile"
if [[ ! -f "$modelfile" ]]; then
  cat > "$modelfile" <<EOF
# Auto-generated by local-llm-agent import-to-ollama.sh
# Edit SYSTEM/PARAMETER and re-run "ollama create $tag -f $modelfile" to apply.

FROM ${gguf}
EOF
  echo "Generated Modelfile: $modelfile"
fi

echo "==> ollama create $tag -f $modelfile"
ollama create "$tag" -f "$modelfile"

# Find the manifest written by ollama (variant is "latest" by default)
case "$tag" in
  */*:*) ns="${tag%/*}"; rest="${tag#*/}"; name="${rest%:*}"; variant="${rest#*:}"; manifest="${MANIFESTS}/${ns}/${name}/${variant}" ;;
  *:*)   name="${tag%:*}"; variant="${tag#*:}";                                 manifest="${MANIFESTS}/library/${name}/${variant}" ;;
  *)     manifest="${MANIFESTS}/library/${tag}/latest" ;;
esac

if [[ ! -f "$manifest" ]]; then
  echo "Manifest not found after create: $manifest" >&2
  exit 1
fi

digest="$(python3 -c '
import json, sys
m = json.load(open(sys.argv[1]))
for layer in m["layers"]:
    if layer["mediaType"] == "application/vnd.ollama.image.model":
        print(layer["digest"].replace(":", "-"))
        sys.exit(0)
sys.exit("no GGUF layer")
' "$manifest")"

cas_blob="${CAS}/${digest}"
if [[ -L "$cas_blob" ]]; then
  echo "CAS blob is already a symlink (already shared): $cas_blob"
  exit 0
fi

echo "==> Collapsing duplicate: replace CAS copy with symlink to ${gguf}"
sudo -A -p '' rm "$cas_blob"
sudo -A -p '' ln -s "$gguf" "$cas_blob"

echo "Done. ${tag} now uses ${gguf}; CAS contains a symlink only."
