#!/usr/bin/env python3
"""Generate Modelfiles from personalities.py and run `ollama create` for each.

Idempotent: skips models whose Modelfile already matches the desired content
and whose target model is already installed.

Usage:
    python build.py                  # build all personalities
    python build.py mistral-local    # build only listed personalities
    python build.py --force          # rebuild even if up-to-date
"""

from __future__ import annotations

import argparse
import os
import json
import subprocess
import sys
import urllib.request
from pathlib import Path

from personalities import PERSONALITIES

LOCAL_LLM_AGENT_ROOT = Path(
    os.environ.get("LOCAL_LLM_AGENT_ROOT", Path(__file__).resolve().parents[1])
).resolve()
MODELFILES_DIR = Path(
    os.environ.get(
        "MODELFILES_DIR",
        LOCAL_LLM_AGENT_ROOT / "modelfiles" / "personalities",
    )
)
OLLAMA_HOST = os.environ.get("OLLAMA_HOST", "127.0.0.1:11434")


def render_modelfile(name: str, spec: dict) -> str:
    lines = [
        f"# Output model: {name}",
        "# Generated by local-llm-agent tuning/build.py",
        "# Edit tuning/personalities.py and rerun.",
        "",
        f"FROM {spec['base']}",
    ]
    system = spec["system"].strip()
    if "\n" in system or '"' in system:
        lines.append(f'SYSTEM """\n{system}\n"""')
    else:
        lines.append(f"SYSTEM {system}")
    for key, value in spec.get("params", {}).items():
        lines.append(f"PARAMETER {key} {value}")
    for stop in spec.get("stops", []):
        lines.append(f"PARAMETER stop {stop}")
    return "\n".join(lines) + "\n"


def installed_models() -> set[str]:
    req = urllib.request.Request(f"http://{OLLAMA_HOST}/api/tags")
    with urllib.request.urlopen(req, timeout=10) as resp:
        data = json.loads(resp.read())
    names: set[str] = set()
    for m in data.get("models", []):
        names.add(m["name"])
        if m["name"].endswith(":latest"):
            names.add(m["name"][: -len(":latest")])
    return names


def build_one(name: str, spec: dict, force: bool, installed: set[str]) -> str:
    target_modelfile = MODELFILES_DIR / f"{name}.Modelfile"
    desired = render_modelfile(name, spec)

    base = spec["base"]
    if base not in installed:
        return f"SKIP {name}: base '{base}' not installed"

    modelfile_unchanged = (
        target_modelfile.exists() and target_modelfile.read_text() == desired
    )
    target_present = name in installed or f"{name}:latest" in installed

    if modelfile_unchanged and target_present and not force:
        return f"OK   {name}: up-to-date"

    target_modelfile.parent.mkdir(parents=True, exist_ok=True)
    target_modelfile.write_text(desired)

    result = subprocess.run(
        ["ollama", "create", name, "-f", str(target_modelfile)],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        return f"FAIL {name}: {result.stderr.strip()}"
    return f"BUILT {name}: {target_modelfile}"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("names", nargs="*", help="Subset of personalities to build")
    parser.add_argument("--force", action="store_true", help="Rebuild even if up-to-date")
    args = parser.parse_args()

    if args.names:
        unknown = [n for n in args.names if n not in PERSONALITIES]
        if unknown:
            print(f"Unknown personalities: {', '.join(unknown)}", file=sys.stderr)
            print(f"Known: {', '.join(sorted(PERSONALITIES))}", file=sys.stderr)
            return 2
        targets = {n: PERSONALITIES[n] for n in args.names}
    else:
        targets = PERSONALITIES

    try:
        installed = installed_models()
    except Exception as exc:
        print(f"Cannot reach Ollama API at {OLLAMA_HOST}: {exc}", file=sys.stderr)
        print(
            f"Run {LOCAL_LLM_AGENT_ROOT}/scripts/ollama/serve.sh first.",
            file=sys.stderr,
        )
        return 1

    rc = 0
    for name, spec in targets.items():
        line = build_one(name, spec, args.force, installed)
        print(line)
        if line.startswith("FAIL"):
            rc = 1
    return rc


if __name__ == "__main__":
    sys.exit(main())
